[package]
name = "chogalyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
rand = "0.8.5"
tabled = "0.17.0"

[profile.release]
codegen-units = 1
lto = "fat"
debug = 1

[build]
rustflags = ["-C", "target-cpu=native"]
